### PR TITLE
adjust location of default cert.pem

### PR DESCRIPTION
**Pull request by JedMeister**
I'm currently doing this for all Apache apps; done this one manually...

### CODE REVIEW

**Comment by qrntz** [comment]
@JedMeister, I feel like it would be better to remove the ```SSLCertificateFile``` directive altogether. We are, after all, aiming to centralize the settings.

**Comment by JedMeister** [comment]
@qrntz - True & it is in the shared conf (ssl mod IIRC). However I also included it in the site/vhost conf for 2 reasons. 

The first may no be very good; but the second is good enough for me...! :smile: I'm still open to disagreement but you'll need to be convincing! :smile: 

1. I strongly suspect that if we don't have it declared in the site/vhost conf we'll get lots of peeps asking about it on the support forums...

2. I'd like it to be consistent. Now that I have already done this with lighty apps and I have PRs already for most of the Apache ones too; IMO it's easier to continue and do the few that remain rather than backtrack and redo it...

**Comment by qrntz** [comment]
@JedMeister,

1. Doesn't matter much IMO, if one needs another cert/more settings, the virtual host setting overrides the default anyway. And you only have to answer the question once if it arises anyway, it's not like TKL offers support by phone. (or do we? :-)

2. Oh well, I've made a point of removing that line from appliances I've worked on lately… and I believe for good reason. As I said, we aim for centralizing the configuration and having duplicate directives only serves to leave loose ends if we have to change it again in the future. Or if Apache change their conf syntax/layout.<sup>1</sup> So there's a chance you'll have to go over the stuff again anyway if you don't now. Besides, you don't really have to fully «backtrack» per se — interactive rebase/amend helps. I believe that you can overwrite Git history in PR branches freely (within reason) because:

  * Until it is not merged, it is (generally) not pulled — you will not break other people's repositories;

  * A neat PR goes a long way.

If you want, I can do that (and the commits won't even have the annoying «committed by» label). Obviously I'll have to open another PR for that though. Or I can give you code to do this automatically for a number of repos by name.

<sup>1</sup> To be frank, if it was me in charge, I'd even put the VirtualHost entries and other boilerplate in the default config and include appliance-specific stuff from there.

**Comment by JedMeister** [comment]
Hmmm... You're quite convincing! TBH more convincing that I anticipated! :smile: 

I guess you're right. I could just commit the code squash it into the last commit (i.e. --amend) then just force GH to sync with my local repo. FWIW I actually did that the other day so I should be good with that, although TBH I don't recall the command I used to force GH...

Ok you've convinced me...! Let's ditch the cert file in Apache confs... I'll also move it in lighty too... I have all the apache repos already

**Comment by qrntz** [comment]
The command to force a push is

    git push -f origin <branch>

**Comment by JedMeister** [comment]
Easy, cheers...

**Pull request closed without merging**
